
import {  ConnectButton } from '@rainbow-me/rainbowkit';

import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { useState } from 'react';

import { useBridgePointless, useTotalCustomFees } from '../hooks/useBridgePointless';
import { useStorageAt } from 'wagmi';

export
  default function
  Home() {

  const [number,setNumber] = useState('');

  const [loading, setLoading] = useState(false);

  const bridgePointless = useBridgePointless(number);
  
  const totalCustomFees = useTotalCustomFees();


  const
    handleChange = (e) => {
      //console.log(e.target.value);
      setNumber(e.target.value);
    };



  const
    handleSubmit = async () => {
        setLoading(true);
        try {
          console.log(Number(number))
          console.log(await totalCustomFees());
          await bridgePointless(Number(number));
        } catch (err) {
          //console.error(err);
        } finally {
          setLoading(false);
        }

      };

  return (

    <div
      className={styles.container}>

      <Head>
        <title>pointless test bridge</title>

        <meta

          content="Generated by @rainbow-me/create-rainbowkit"

          name="pointless test bridge"

        />

        <link
          href="/favicon.ico"
          rel="icon"
        />

      </Head>



      <main
        className={styles.main}>

        <ConnectButton
        />

        <div>

          <h1>Pointless bridge</h1>
          <p>Important: Ensure you have enough ptless tokens(CA: 0x427C2E7F6ad74c124CD6F33E317891D26fB38efe) approved to be spent by the bridge contract(CA: 0x57Dd4Fea22E2344f6C7f6d3185C130c6B2E17a1C)</p>
          <p>Select Polygon network in the drop down above</p>
          
          <input

            type="number"

            value={number}

            onChange={handleChange}

            placeholder="Amount to send"

          />

          <button
            onClick={handleSubmit}
            disabled={loading}>

            {loading
              ?
              'Processing...' :
              'Submit'}

          </button>

        </div>


      </main>



      <footer
        className={styles.footer}>

        <a
          href="https://rainbow.me"
          rel="noopener noreferrer"
          target="_blank">

          Made with ❤️ by your frens at 🌈

        </a>

      </footer>

    </div>

  );

};



//export default Home;
