import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { useState, useEffect } from 'react';

import Link from 'next/link';
import Image from 'next/image';

export
  default function
  Home() {

  return (

    <div
      className={styles.container}>

      <Head>
        <title>pointless</title>

        <meta

          content="Generated by @rainbow-me/create-rainbowkit"

          name="pointless"

        />

        <link
          href="/images/favicon.ico"
          rel="icon"
        />

      </Head>

      <main
        className={styles.main}>


        
    <div>
      <h1>$pointless is the goat(ed) coin of the Lens protocol</h1>
      <Image
        src="/images/ptgoat.gif"  // Path relative to the public directory
        alt="pointless unigoat with a spinning ball attached to its unihorn..."
        width={500}           // Set the width
        height={500}          // Set the height
      /> <br />
      <Link href="/tokeninfo" >
        <button className={styles.customButton}>Token Info</button>
      </Link>
      <Link href="/origin" >
        <button className={styles.customButton}>Pointless Origins</button>
      </Link>
      <Link href="/bridge" >
        <button className={styles.customButton}>Bridge</button>
      </Link>
    </div>


      </main>



      <footer
        className={styles.footer}>

        <a
          href="https://rainbow.me"
          rel="noopener noreferrer"
          target="_blank">

          Made with ❤️ by @sydney-bro

        </a>

      </footer>

    </div>

  );

};



//export default Home;
