import Head from 'next/head';

import styles from '../styles/Home.module.css';

import { useState, useEffect } from 'react';

import Link from 'next/link';

export
  default function
  origin() {

  return (

    <div
      className={styles.container}>

      <Head>
        <title>pointless</title>

        <meta

          content="Generated by @rainbow-me/create-rainbowkit"

          name="pointless"

        />

        <link
          href="images/favicon.ico"
          rel="icon"
        />

      </Head>

      <main
        className={styles.main}>


        
    <div>
      <h2>$pointless Origin Story</h2>
      <aside className="origin-panel" >
      <p>$pointless was born when the official lens handle teased a points program <br />
      <img src="/images/lenspt.jpeg" /> <br />
      Airdrop mania was at its peak and a number of projects launched a points program <br />
      Most of the points programs turned out to have a farm the farmer objective rather than actual community building <br />
      $pointless was launched as a funny reaction to these devious points programs <br />
      $pointless had a very pointless airdrop with some obvisouly pointless rules <br />
      
      <ul>
        <li>First 10 people who commented on sydney-bro's post got 1% of the $pointless supply</li> 
        <li>Next people to comment all got 100M pointless</li>
        <li>Anyone who merely liked the post got 20M pointless</li>
        <li>All addresses that held a lens profile NFT on 15th Dec 2023 got 5M $pointless</li>
      </ul>
      All in all, more than 73% of the supply was airdropped on day 1 <br />
      <a href="https://app.t2.world/article/clssqalm04365021zmcmovy2s5j" >Read the full story</a> <br />
      <a href="https://app.t2.world/article/cltl3xefq131102520mcnny9lw1j">Read about the lens OGs who helped shape pointless in the initial stages</a>
      </p>
      </aside> 
       <br />
      <Link href="/">
        <button className={styles.customButton}>Home</button>
      </Link>
      <Link href="/bridge">
        <button className={styles.customButton}>Bridge</button>
      </Link>

    </div>


      </main>



      <footer
        className={styles.footer}>

        <a
          href="https://rainbow.me"
          rel="noopener noreferrer"
          target="_blank">

          Made with ❤️ by @sydney-bro

        </a>

      </footer>

    </div>

  );

};



//export default Home;
